/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkkp;

/**
 *
 * @author ASUS
 */

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import javax.swing.*;
import javax.swing.JComboBox;
import koneksi.condatabase;

public class peserta extends javax.swing.JFrame {

    Connection Con;
    ResultSet rsPeserta;
    Statement stm;
    Boolean ada = false;
    String skck;
    Boolean edit = false;

    private Object[][] dataTable = null;
    private String[] header = { "ID", "Nama Lengkap", "Provinsi", "Kabupaten", "Kecamatan", "Alamat", "Email",
            "Telepon", "IPK", "SKCK" };

    public peserta() {
        initComponents();
        conDatabase();
        readData();
        aktif(false);
        setTombol(true);
    }

    private void setField() {
        int row = tblPeserta.getSelectedRow();
        txtId.setText((String) tblPeserta.getValueAt(row, 0));
        txtNama.setText((String) tblPeserta.getValueAt(row, 1));
        txtProvinsi.setText((String) tblPeserta.getValueAt(row, 2));
        txtKab.setText((String) tblPeserta.getValueAt(row, 3));
        txtKec.setText((String) tblPeserta.getValueAt(row, 4));
        txtAlmt.setText((String) tblPeserta.getValueAt(row, 5));
        txtEmail.setText((String) tblPeserta.getValueAt(row, 6));
        txtTelp.setText((String) tblPeserta.getValueAt(row, 7));
        String ipk = Double.toString((Double) tblPeserta.getValueAt(row, 8));
        txtIpk.setText(ipk);
        cbSkck.setSelectedItem((String) tblPeserta.getValueAt(row, 9));
    }

    private void conDatabase() {
        try {
            condatabase connect = new condatabase("localhost", "root", "", "dbpkkp");
            Con = connect.getConnection();
        } catch (Exception e) {
            System.out.println("Error : " + e);
        }
    }

    private void readData() {
        try {
            stm = Con.createStatement();
            rsPeserta = stm.executeQuery("select * from peserta");
            ResultSetMetaData meta = rsPeserta.getMetaData();
            int col = meta.getColumnCount();
            int baris = 0;
            while (rsPeserta.next()) {
                baris = rsPeserta.getRow();
            }
            dataTable = new Object[baris][col];
            int x = 0;
            rsPeserta.beforeFirst();
            while (rsPeserta.next()) {
                dataTable[x][0] = rsPeserta.getString("idPeserta");
                dataTable[x][1] = rsPeserta.getString("nama");
                dataTable[x][2] = rsPeserta.getString("prov");
                dataTable[x][3] = rsPeserta.getString("kab");
                dataTable[x][4] = rsPeserta.getString("kec");
                dataTable[x][5] = rsPeserta.getString("alamat");
                dataTable[x][6] = rsPeserta.getString("email");
                dataTable[x][7] = rsPeserta.getString("telp");
                dataTable[x][8] = rsPeserta.getString("ipk");
                dataTable[x][9] = rsPeserta.getString("skck");
                x++;
            }
            tblPeserta.setModel(new DefaultTableModel(dataTable, header));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void kosong() {
        txtId.setText("");
        txtNama.setText("");
        txtProvinsi.setText("");
        txtKab.setText("");
        txtKec.setText("");
        txtAlmt.setText("");
        txtEmail.setText("");
        txtTelp.setText("");
        txtIpk.setText("");
    }

    private void aktif(boolean x) {
        txtId.setEditable(x);
        txtNama.setEditable(x);
        txtProvinsi.setEditable(x);
        txtKab.setEditable(x);
        txtKec.setEditable(x);
        txtAlmt.setEditable(x);
        txtEmail.setEditable(x);
        txtTelp.setEditable(x);
        txtIpk.setEditable(x);
    }

    private void setTombol(boolean t) {
        cmbDaftar.setEnabled(!t);
        cmbInput.setEnabled(t);
        cmbEdit.setEnabled(t);
        cmbHapus.setEnabled(t);
        cmbBatal.setEnabled(!t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtProvinsi = new javax.swing.JTextField();
        txtKab = new javax.swing.JTextField();
        txtKec = new javax.swing.JTextField();
        txtAlmt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTelp = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtIpk = new javax.swing.JTextField();
        cbSkck = new javax.swing.JComboBox<>();
        cmbInput = new javax.swing.JButton();
        cmbDaftar = new javax.swing.JButton();
        cmbEdit = new javax.swing.JButton();
        cmbHapus = new javax.swing.JButton();
        cmbBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeserta = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id Peserta");

        jLabel2.setText("Nama Lengkap");

        jLabel3.setText("Provinsi");

        jLabel4.setText("Kabupaten");

        jLabel5.setText("Kecamatan");

        jLabel6.setText("Alamat");

        jLabel7.setText("IPK");

        jLabel8.setText("Email");

        jLabel9.setText("Telepon");

        jLabel10.setText("SKCK");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        cbSkck.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Melampirkan", "Tidak Melampirkan" }));
        cbSkck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSkckActionPerformed(evt);
            }
        });

        cmbInput.setBackground(new java.awt.Color(0, 0, 255));
        cmbInput.setForeground(new java.awt.Color(255, 255, 255));
        cmbInput.setText("Input");
        cmbInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbInputActionPerformed(evt);
            }
        });

        cmbDaftar.setBackground(new java.awt.Color(0, 0, 255));
        cmbDaftar.setForeground(new java.awt.Color(255, 255, 255));
        cmbDaftar.setText("Daftar");
        cmbDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDaftarActionPerformed(evt);
            }
        });

        cmbEdit.setBackground(new java.awt.Color(0, 0, 255));
        cmbEdit.setForeground(new java.awt.Color(255, 255, 255));
        cmbEdit.setText("Edit");
        cmbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEditActionPerformed(evt);
            }
        });

        cmbHapus.setBackground(new java.awt.Color(0, 0, 255));
        cmbHapus.setForeground(new java.awt.Color(255, 255, 255));
        cmbHapus.setText("Hapus");
        cmbHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHapusActionPerformed(evt);
            }
        });

        cmbBatal.setBackground(new java.awt.Color(0, 0, 255));
        cmbBatal.setForeground(new java.awt.Color(255, 255, 255));
        cmbBatal.setText("Batal");
        cmbBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBatalActionPerformed(evt);
            }
        });

        tblPeserta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Peserta", "Nama Lengkap", "Provinsi", "Kabupaten", "Kecamatan", "Alamat", "Email", "Telepon", "IPK", "SKCK"
            }
        ));
        tblPeserta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPesertaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPeserta);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Daftar Peserta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbDaftar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbBatal)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNama)
                                            .addComponent(txtId)
                                            .addComponent(txtProvinsi)
                                            .addComponent(txtKab)
                                            .addComponent(txtKec)
                                            .addComponent(txtAlmt, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbSkck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtTelp, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                                .addComponent(txtEmail)
                                                .addComponent(txtIpk, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(cmbInput))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtIpk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cbSkck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAlmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDaftar)
                    .addComponent(cmbEdit)
                    .addComponent(cmbHapus)
                    .addComponent(cmbBatal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSkckActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbSkckActionPerformed
        JComboBox tskck = (javax.swing.JComboBox) evt.getSource();
        skck = (String) tskck.getSelectedItem();
    }

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//
        // GEN-FIRST:event_txtEmailActionPerformed

    }

    private void cmbInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmbInputActionPerformed
        aktif(true);
        setTombol(false);
        kosong();
    }

    private void cmbDaftarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmbDaftarActionPerformed
        String idPeserta = txtId.getText();
        String nama = txtNama.getText();
        String prov = txtProvinsi.getText();
        String kab = txtKab.getText();
        String kec = txtKec.getText();
        String alamat = txtAlmt.getText();
        String email = txtEmail.getText();
        String telp = txtTelp.getText();
        double ipk = Double.parseDouble(txtIpk.getText());
        try {
            if (edit == true) {
                stm.executeUpdate("update peserta set nama='" + nama + "',prov='" + prov
                        + "',kab='" + kab + "',kec='" + kec + "',alamat='" + alamat + "',email='" + email + "',telp='"
                        + telp + "',ipk=" + ipk + ",skck='" + skck + "' where idPeserta='" + idPeserta + "'");
            } else {
                stm.executeUpdate("insert into peserta values('" + idPeserta + "' , '" + nama + "', '" + prov
                        + "', '" + kab + "', '" + kec + "', '" + alamat + "', '" + email + "','" + telp + "'," + ipk
                        + ", '" + skck + "')  ");
            }
            tblPeserta.setModel(new DefaultTableModel(dataTable, header));
            readData();
            aktif(false);
            setTombol(true);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
        }

    }

    private void cmbEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmbEditActionPerformed
        edit = true;
        aktif(true);
        setTombol(false);
        txtId.setEditable(false);
    }

    private void cmbHapusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmbHapusActionPerformed
        try {
            String sql = "delete from peserta where idPeserta='" + txtId.getText() + "' ";
            stm.executeUpdate(sql);
            readData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
        }
    }

    private void cmbBatalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmbBatalActionPerformed
        kosong();
        aktif(false);
        setTombol(true);
    }

    private void tblPesertaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tblPesertaMouseClicked
        setField();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(peserta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(peserta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(peserta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(peserta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new peserta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbSkck;
    private javax.swing.JButton cmbBatal;
    private javax.swing.JButton cmbDaftar;
    private javax.swing.JButton cmbEdit;
    private javax.swing.JButton cmbHapus;
    private javax.swing.JButton cmbInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPeserta;
    private javax.swing.JTextField txtAlmt;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIpk;
    private javax.swing.JTextField txtKab;
    private javax.swing.JTextField txtKec;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtProvinsi;
    private javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables
}
